import type { Metadata } from "next";

import { HomeHeader } from "@/components/header/Header";
import { HomeFooter } from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "My first Next Application",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HomeHeader />
      {children}
      <HomeFooter />
    </>
  );
}
